name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          
      # Add caching to speed up deployment
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies and build
        run: |
          npm ci
          npm ci --prefix depo79
          npm run build --prefix depo79
          
      # Create a .env file with the needed variables
      - name: Create environment file
        run: |
          echo "NODE_ENV=production" > .env
          echo "PORT=8080" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "SITE_KEY=${{ secrets.SITE_KEY }}" >> .env
          echo "CLOUDFLARE_SECRET_KEY=${{ secrets.CLOUDFLARE_SECRET_KEY }}" >> .env
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
          echo "ADMIN_SECRET_KEY=${{ secrets.ADMIN_SECRET_KEY }}" >> .env
          echo "IMAGE_STORAGE_KEY=${{ secrets.IMAGE_STORAGE_KEY }}" >> .env
          echo "IMAGE_STORAGE_SECRET=${{ secrets.IMAGE_STORAGE_SECRET }}" >> .env
          echo "FRONTEND_URL=https://internship-bngefpfzewbrd8dw.southeastasia-01.azurewebsites.net" >> .env

      # Create a clean deployment package
      - name: Create deployment directory
        run: |
          # Create ALL necessary directories first
          mkdir -p deployment_package
          mkdir -p deployment_package/depo79
          mkdir -p deployment_package/depo79/dist

      # Modify package.json files
      - name: Create deployment package.json
        run: |
          cat package.json | jq '.scripts.build = "echo Frontend already built"' | jq '.scripts.start = "node backend/server.js"' > deployment_package/package.json
          
      # Modify depo79 package.json to prevent build failures
      - name: Modify depo79 package.json
        run: |
          cat depo79/package.json | jq '.scripts.build = "echo Frontend already built - skipping tsc build"' > deployment_package/depo79/package.json
          
      # Complete the deployment package
      - name: Copy deployment files and prepare for Azure
        run: |
          # Copy backend directory with all subdirectories
          cp -r backend deployment_package/
          
          # Copy frontend files
          mkdir -p deployment_package/depo79/dist
          cp -r depo79/dist/* deployment_package/depo79/dist/
          
          # Copy other required files
          cp package.json deployment_package/
          cp package-lock.json deployment_package/
          cp .env deployment_package/
          
          # Install production dependencies inside deployment_package
          cd deployment_package
          npm install --production
          
          # Add a .deployment file with stronger setting
          echo '[config]' > .deployment
          echo 'SCM_DO_BUILD_DURING_DEPLOYMENT=false' >> .deployment
          echo 'WEBSITE_NODE_DEFAULT_VERSION=~20' >> .deployment
          
          # Create Web.config for Azure
          echo '<?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <webSocket enabled="true" />
              <handlers>
                <add name="iisnode" path="backend/server.js" verb="*" modules="iisnode" />
              </handlers>
              <rewrite>
                <rules>
                  <rule name="backend">
                    <match url="/*" />
                    <action type="Rewrite" url="backend/server.js" />
                  </rule>
                </rules>
              </rewrite>
              <iisnode
                nodeProcessCommandLine="node --experimental-specifier-resolution=node"
                watchedFiles="web.config;*.js"
                loggingEnabled="true"
              />
            </system.webServer>
          </configuration>' > web.config
          
          # Create zip from clean directory
          zip -r ../deploy.zip .
          cd ..

      # Add a step to fix server.js
      - name: Fix ES module imports in server.js
        run: |
          # Create a temporary fixed version of server.js
          cat backend/server.js | sed 's/require(\x27fs\x27)/fs/g' > backend/server.js.fixed
          mv backend/server.js.fixed backend/server.js
          
          # Add fs import at the top of the file
          sed -i '1s/^/import fs from "fs";\n/' backend/server.js

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "Internship"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./deploy.zip